### ISSUE TITLE
Black tiles with non-square images

### ISSUE THREAD

**Issue by ingdanielguerrero** [davidbrochart/xarray_leaflet#21] opened 2020-10-12 18:30 UTC
I'm trying to display a raster image in an ipyleaflet map but there is a black tile in the background, I suspect that it might be related to the shape of the image but I can't display it in a good way, this is the code I'm using.

```Python
import rioxarray
import numpy as np
import ipyleaflet
import xarray_leaflet

map_ = ipyleaflet.Map()

da = rioxarray.open_rasterio(image, masked=True)
da = da.rio.write_nodata(np.nan)
da = da.sel(band=1)

da.leaflet.plot(map_)

l,b,r,t=da.rio.bounds()
lat = (t-b)/2 + b
lon = (r-l)/2 + l
map_.center=(lat,lon)

map_
```
This is my env:
rioxarray version '0.1.0'
ipyleaflet version '0.13.3'
xarray_leaflet version '0.1.10'

An this is what I'm getting:

![image](https://user-images.githubusercontent.com/12363250/95779084-af10b680-0cc9-11eb-921b-b3a764f60a70.png)

**Comment by davidbrochart** [comment] 2020-10-12 19:16
Can you share your data somehow, so that I can reproduce?

**Comment by ingdanielguerrero** [comment] 2020-10-12 19:22
Sure, here is one of the rasters https://drive.google.com/file/d/1o3ejsXsGc0vG2UTvW_bX8FmEz3tmXPeg

**Comment by davidbrochart** [comment] 2020-10-12 23:18
Thanks, I just fixed it locally. I will release a new version soon.
BTW in the new version you won't have to center the map on your array, it will be done automatically.

**Comment by crendl** [comment] 2020-10-13 10:49
just fyi, i remember a similar/or same issue when a colleague tried to reproduce a notebook, eventually we had different matplotlib versions. updating to the newest version solved it for us.

Name: matplotlib
Version: 3.3.2

**Comment by davidbrochart** [comment] 2020-10-13 11:05
Interesting, I'm wondering how it could be related. Maybe updating matplotlib also updated another package.
But in this case the `nodata` attribute from `rioxarray` was lost somewhere during the tile generation. I solved it by saving before any processing and reapplying it just before reprojection, because rioxarray needs to pass it to rasterio.

**Comment by davidbrochart** [comment] 2020-10-13 14:24
Version 0.1.11 has been released in PyPI (soon on conda-forge), let me know how it goes!

**Closed by davidbrochart** 2020-10-13 14:24 UTC

**Comment by ingdanielguerrero** [comment] 2020-10-19 15:57
Thank you @davidbrochart, it's working perfectly with the 0.1.12 version.
